spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9091/realms/gateway-service"
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888

