spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://keycloak:9091/realms/gateway-service"
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://config-server:8888

