# db-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: microservices
type: Opaque
data:
  POSTGRES_USER: dGVzdA==       # base64 of 'test'
  POSTGRES_PASSWORD: dGVzdA==   # base64 of 'test'
  MONGO_INITDB_ROOT_USERNAME: dGVzdA==
  MONGO_INITDB_ROOT_PASSWORD: dGVzdA==