# keycloak-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.2
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"        # Minimum CPU requested (0.2 vCPU)
              memory: "256Mi"    # Minimum memory requested
            limits:
              cpu: "500m"        # Max CPU allowed (0.5 vCPU)
              memory: "512Mi"    # Max memory allowe
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
          args: ["start-dev"]
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: microservices
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080