apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: microservices
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
  PGADMIN_DEFAULT_PASSWORD: admin123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:8.6
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: PGADMIN_DEFAULT_PASSWORD
          volumeMounts:
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin
      volumes:
        - name: pgadmin-data
          emptyDir: {}   # For persistence, replace with PVC
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: microservices
spec:
  type: NodePort   # Change to ClusterIP if you only access from inside the cluster
  selector:
    app: pgadmin
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30050   # Access it from your VM: http://<VM-IP>:30050
