spring:
  data:
    mongodb:
      authentication-database: admin
      username: test
      password: test
      host: mongodb
      port: 27017
      database: customer
server:
  port: 8090
eureka:
  instance:
  prefer-ip-address : true
  hostname : customer
