server:
  port: 8099
spring:
  data:
    mongodb:
      username: test
      password: test
      host: mongodb
      port: 27017
      database: notification
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.project.ecommerce.kafka.order.OrderConfirmation,paymentConfirmation:com.project.ecommerce.kafka.payment.PaymentConfirmation
  mail:
    host: maildev
    port: 1025
    username: alibou
    password: alibou
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
