apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: elmahdidevops/customer:latest
          ports:
            - containerPort: 8090
          resources:
            requests:
              cpu: "200m"        # Minimum CPU requested (0.2 vCPU)
              memory: "256Mi"    # Minimum memory requested
            limits:
              cpu: "900m"        # Max CPU allowed (0.5 vCPU)
              memory: "512Mi"    # Max memory allowed
---
# customer-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: customer
  namespace: microservices
spec:
  selector:
    app: customer
  ports:
    - port: 8090
      targetPort: 8090
