# customer-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: elmahdidevops/customer:latest
          ports:
            - containerPort: 8090
---
# customer-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: customer
  namespace: microservices
spec:
  selector:
    app: customer
  ports:
    - port: 8090
      targetPort: 8090
