apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery
  template:
    metadata:
      labels:
        app: discovery
    spec:
      containers:
        - name: discovery
          image: elmahdidevops/discovery:latest
          ports:
            - containerPort: 8761
          resources:
            requests:
              cpu: "200m"        # Minimum CPU requested (0.2 vCPU)
              memory: "256Mi"    # Minimum memory requested
            limits:
              cpu: "900m"        # Max CPU allowed (0.5 vCPU)
              memory: "512Mi"    # Max memory allowe
---
apiVersion: v1
kind: Service
metadata:
  name: discovery
  namespace: microservices
spec:
  type: ClusterIP
  selector:
    app: discovery
  ports:
    - port: 8761
      targetPort: 8761
