# notification-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: elmahdidevops/notification:latest
          ports:
            - containerPort: 8099
          resources:
            requests:
              cpu: "200m"        # Minimum CPU requested (0.2 vCPU)
              memory: "256Mi"    # Minimum memory requested
            limits:
              cpu: "500m"        # Max CPU allowed (0.5 vCPU)
              memory: "512Mi"    # Max memory allowe
---
# notification-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: microservices
spec:
  selector:
    app: notification
  ports:
    - port: 8099
      targetPort: 8099
