# order-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: elmahdidevops/order:latest
          ports:
            - containerPort: 8095
---
# order-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: microservices
spec:
  selector:
    app: order
  ports:
    - port: 8095
      targetPort: 8095
