# product-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: elmahdidevops/product:latest
          ports:
            - containerPort: 8050
---
# product-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: microservices
spec:
  selector:
    app: product
  ports:
    - port: 8050
      targetPort: 8050
